layout_spectrum: 0.7953692
favicon: null
name: Christopher Hoffman
purpose: []
analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
cta:
  version: null
  bucket: null
  domain: null
color:
  brandStrength: 0.4442256521433592
  saturation: 0.07533890171907842
  brandColors:
    - '#000000'
    - '#cdcdcd'
    - '#9e9e9e'
    - '#5a5a5a'
    - '#7d7d7d'
  lightness: 0.3753202946390957
  rhythmicContrast: 0.6580135200638324
typography_spectrum: 0.9156906232237816
